//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Spres.Models
{
    using System.Collections.Generic;
    using System.Linq;

    public class Account
    {
        public Account()
        {
            Children = new HashSet<Account>();
            Packages = new HashSet<Package>();
        }
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Display { get {return string.Format("{0} {1}", Code, Name); } }

        public string TypeDescription
        {
            get
            {
                return string.Join(", ", Type.Split(',').Select(t =>
                                (t == "P") ? "Planta" :
                                (t == "M") ? "Manufactura" :
                                (t == "A") ? "Administración" :
                                (t == "F") ? "Financiero" :
                                (t == "C") ? "Mercadeo" : "Otros"
                            ));
            }
        }

        public string PackagesDescription
        {
            get
            {
                return string.Join(", ", Packages.Select(p => p.Name).ToList());
            }
        }
        public virtual int? ParentId { get; set; }
        public virtual Account Parent { get; set; }
        public virtual ICollection<Account> Children { get; set; }
        public virtual ICollection<Package> Packages { get; set; }                 
    }

   
}

