//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Spres.Models
{
    public class Benefit
    {
        public Benefit()
        {
            this.Code = "DefaultCode";
        }

        public int Id { get; set; }

        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Value { get; set; }
        public BenefitTargetType Target { get; set; }
    }
}

