//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
namespace Spres.Models
{

    public class BudgetMonthDetail
    {

        public BudgetMonthDetail()
        {
            Histories = new HashSet<BudgetMonthHistory>();
        }

        public int Id { get; set; }

        public int LineId { get; set; }
        public virtual BudgetLine Line { get; set; }



        public int Month { get; set; }
        public int Quantity { get; set; }
        public decimal UnitCost { get; set; }
        public decimal Target { get; set; }
        public decimal Forecast { get; set; }
        //XML
        public string ExpenseDetail { get; set; }
        public decimal Real { get; set; }

        public virtual ICollection<BudgetMonthHistory> Histories { get; set; }
    }
}

