//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Spres.Models
{
    using System.Collections.Generic;

    public class BudgetSheet
    {
        public BudgetSheet()
        {
            Lines = new HashSet<BudgetLine>();
        }
        public int Id { get; set; }


        public int BudgetId { get; set; }
        public virtual Budget Budget { get; set; }


        public int PackageId { get; set; }
        public virtual Package Package { get; set; }

        public virtual ICollection<BudgetLine> Lines { get; set; }
    }
}

