//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Spres.Models
{

    public class Company
	{
        public Company()
        {
            Authorizers = new HashSet<CompanyAuthorizer>();
        }

		public  int Id { get; set; }
		public  string Name { get; set; }
		public  string Country { get; set; }

        public virtual ICollection<CompanyAuthorizer> Authorizers { get; set; }
	}
}

