//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Collections.Generic;

namespace Spres.Models
{
    public class CostCenter
	{
        public CostCenter()
        {
            Children = new HashSet<CostCenter>();
        }
        public int Id { get;set; }
        public string Code { get; set; }
		public string Name { get; set; }
        public string Type { get; set; }
        public string Mirror { get; set; }
        public string Display { get { return string.Format("{0} {1}", Code, Name); } }
        public string TypeDescription
        {
            get
            {
                return string.Join(", ", Type.Split(',').Select(t =>
                              (t == "P") ? "Planta" :
                              (t == "M") ? "Manufactura" :
                              (t == "A") ? "Administración" :
                              (t == "F") ? "Financiero" :
                              (t == "C") ? "Mercadeo" : "Otros"
                          ));
            }
        }

        public virtual int? ParentId { get; set; }
        public virtual CostCenter Parent { get; set; }

        public virtual ICollection<CostCenter> Children { get; set; }

        public string ResponsibleGUID { get; set; }

        public int? CompanyId { get; set; }
        public virtual Company Company { get; set; }

        
	}
}

