//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Spres.Models
{

    public class Premise
    {
        public int Id { get; set; }


        public string Name { get; set; }

        //XML
        public string Expenses { get; set; }        


        public int FiscalYear { get; set; }
        public virtual Programming Programming { get; set; }


        public virtual int CompanyId { get; set; }
        public virtual Company Company { get; set; }


        public virtual int PremiseTypeId { get; set; }
        public virtual PremiseType Type { get; set; }

    }
}

