//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Spres.Models
{

    public class PremiseType
	{
		public  int Id { get; set; }

		public  string Name { get; set; }
        //XML
        public string Definition { get; set; }

	}
}

