// <auto-generated />
namespace Spres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class VictorFlamenc0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VictorFlamenc0));
        
        string IMigrationMetadata.Id
        {
            get { return "201511111904437_VictorFlamenc0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
