// <auto-generated />
namespace Spres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class GustavoRauda6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GustavoRauda6));
        
        string IMigrationMetadata.Id
        {
            get { return "201512291740114_GustavoRauda6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
