// <auto-generated />
namespace Spres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class WaldemarMezquita : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WaldemarMezquita));
        
        string IMigrationMetadata.Id
        {
            get { return "201512121525459_WaldemarMezquita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
