// <auto-generated />
namespace Spres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class VictorFlamenco19 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VictorFlamenco19));
        
        string IMigrationMetadata.Id
        {
            get { return "201602092128453_VictorFlamenco19"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
