//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Account
	{
		public virtual int Id
		{
			get;
			set;
		}

		public virtual string Code
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual Account Parent
		{
			get;
			set;
		}

		public virtual IEnumerable<Account> Children
		{
			get;
			set;
		}

		public virtual Package Package
		{
			get;
			set;
		}

	}
}

