//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BudgetLine
	{
		public virtual string Description
		{
			get;
			set;
		}

		public virtual int Item
		{
			get;
			set;
		}

		public virtual BudgetLine Parent
		{
			get;
			set;
		}

		public virtual IEnumerable<BudgetLine> Children
		{
			get;
			set;
		}

		public virtual IEnumerable<BudgetMonthDetail> Detail
		{
			get;
			set;
		}

		public virtual Account Account
		{
			get;
			set;
		}

		public virtual BudgetSheet Sheet
		{
			get;
			set;
		}

		public virtual Premise Premise
		{
			get;
			set;
		}

	}
}

