//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BudgetMonthDetail
	{
		public virtual int Quantity
		{
			get;
			set;
		}

		public virtual Decimal UnitCost
		{
			get;
			set;
		}

		public virtual Decimal Target
		{
			get;
			set;
		}

		public virtual Decimal Forecast
		{
			get;
			set;
		}

		public virtual Decimal Real
		{
			get;
			set;
		}

		public virtual int Month
		{
			get;
			set;
		}

		public virtual BudgetLine Line
		{
			get;
			set;
		}

	}
}

