//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BudgetSheet
	{
		public virtual IEnumerable<BudgetLine> Lines
		{
			get;
			set;
		}

		public virtual Budget Budget
		{
			get;
			set;
		}

		public virtual Package Package
		{
			get;
			set;
		}

	}
}

