//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Premise
	{
		public virtual object Account
		{
			get;
			set;
		}

		public virtual int FiscalYear
		{
			get;
			set;
		}

		public virtual int Id
		{
			get;
			set;
		}

        //XML
		public virtual string Definition
		{
			get;
			set;
		}

		public virtual Company Company
		{
			get;
			set;
		}

		public virtual PremiseType Type
		{
			get;
			set;
		}

	}
}

