//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Programming
	{
		public virtual int FiscalYear
		{
			get;
			set;
		}

		public virtual DateTime BudgetStartDate
		{
			get;
			set;
		}

		public virtual object BudgetEndDate
		{
			get;
			set;
		}

	}
}

