//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Responsibility
	{
		public virtual IEnumerable<CostCenter> CostCenter
		{
			get;
			set;
		}

		public virtual IEnumerable<Package> Package
		{
			get;
			set;
		}

		public virtual Employee Employee
		{
			get;
			set;
		}

	}
}

