//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Linq;
using System.Text;
using System.Security.Claims;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;

namespace Spres.Infrastructure.Security
{

	public class User : IdentityUser
	{
        public User(): base()
        {
            PasswordTemp = GeneratePasswordTemp();
        }

        public User(string name)
            : base(name)
        {
            PasswordTemp = GeneratePasswordTemp();
        }
        public string PasswordTemp { get; set; }
        public int Status { get; set; }
        public string Name { get; set; }
        private string GeneratePasswordTemp()
        {
            var guidtemp = Guid.NewGuid().ToString();
            return guidtemp.Split('-')[0];
        }

        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<User> manager)
        {
            // Note the authenticationType must match the one defined in CookieAuthenticationOptions.AuthenticationType
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ExternalBearer);
            // Add custom user claims here
            return userIdentity;
        }
	}
}

